### ISSUE TITLE
DIO output auto resets with event based approach 

### ISSUE THREAD

**Issue by ashish-y** [naruxde/revpimodio2#1]
Hi,

My current setup:

RevPI connect plus with DIO I/O module and output O_2 of DIO is connected to input I_2 with a cable.

I'm using this code to get input(I_2) change from revpi DIO.

```
import revpimodio2
import sys
def eventfunction(ioname, iovalue):
       print(iovalue)

if len(sys.argv) > 1:
    pin_input = sys.argv[1]
    rpi = revpimodio2.RevPiModIO(autorefresh=True)
    rpi.handlesignalend()
  
    rpi.io[pin_input].reg_event(eventfunction)
    rpi.mainloop()
else:
    print("Bad parameters - input_pin")
```

When I update the output(O_2) value from 0 to 1 the code gets triggered but it automatically sets the output to 0 after execution. 

Example: `piTest -w O_2,1`

The output I get 
```

True
False

```
Expected:
`True
`

Can't seem to figure out the issue here.

This works fine without adding the event-based approach.

Ashish

**Comment by naruxde** [comment]
Hi Ashish, sorry for the late response!

This behaviour is "right". RevPiModIO has its own IO buffer and forces the Output states of the library during runtime. So, if the O_2 is set to False in the Python program and an external program, like piTest, modifies the process image, RevPiModIO will overwrite that to force the right Output state! This is important if you control a machine to be sure the IOs has the expected values during the hole runtime!

What happens in your script: You start your python program an the value of O_2 is False. You set the value through piTest to True, which will set I_2 to True. RevPiModIO recognises that change to I_2 and fire up your event function (True line). After that, RevPiModIO set the value of O_2 to False, because this is the value the python program has and will force that value in the process image. That means the I_2 went back to False and there is the change of I_2 which will print the False line.

To switch off this enforcement of output values and share the process image with other application from outside of your python program, please use the "direct_output=True" parameter at instantiation.

`rpi = revpimodio2.RevPiModIO(autorefresh=True, direct_output=True)`

NOTE: The name will change in the next versions from "direct_output" to "shared_procimg" or something like that.

Sven

**Comment by ashish-y** [comment]
Thanks for the detailed explanation Sven. 
Appreciate it!

I created a custom node-red node to get/set REVPI's DIOs and revpimodio2 was a big help in that.   

Thanks,
Ashish
